language: go

go:
  - 1.16.3

sudo: required

before_script:
  - go vet ./...
  - env GOOS=linux ARCH=amd64 go build ./impact-oscillator.go

script:
  - go test ./...

after_success:
  - zip -r imposcg.zip .
  - zipinfo imposcg.zip
  - mkdir lambda-build 2>/dev/null
  - mv imposcg.zip lambda-build/$(bash ./terraform/get_source_archive.bash)

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  - on:
      branch: main
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: felixdux-imposcg-lambda
    skip_cleanup: true
    region: $AWS_DEFAULT_REGION
    local_dir: ./lambda-build
  - on:
      branch: main
    provider: lamdba
    function_name: "ImpactOscillator"
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    role: $IMPOSCG_IAM_ROLE    
    module_name: "impact" # Horrible fudge - travis constructs handler from <module_name>.<handler_name>, defaults module_name to 'index' and won't accept an empty string
    handler_name: "oscillator"
    runtime: "go1.x"
