FROM golang:1.16.3-buster
# RUN go get -u github.com/beego/bee
ENV GO111MODULE=on
ENV GOFLAGS=-mod=mod
ENV APP_USER app
ENV APP_HOME /go/src/imposcg
RUN mkdir -p $APP_HOME 
WORKDIR $APP_HOME
COPY . .
EXPOSE 8080
# CMD ["bee", "run"]
CMD ["go", "test", "./..."]